//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace es.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLogs
    {
        public int AuditID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Action { get; set; }
        public Nullable<int> ContentID { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual Users Users { get; set; }
    }
}
