//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace es.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referrals
    {
        public int ReferralID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ReferralName { get; set; }
        public string ReferralEmail { get; set; }
        public string ReferralComments { get; set; }
        public Nullable<System.DateTime> ReferralDate { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
