//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace es.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int VideoID { get; set; }
        public Nullable<int> ContentID { get; set; }
        public string VideoTitle { get; set; }
        public string VideoDescription { get; set; }
        public string VideoURL { get; set; }
        public string VideoSource { get; set; }
    
        public virtual Content Content { get; set; }
    }
}
