//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace es.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoWatch
    {
        public int VideoWatchID { get; set; }
        public int UserID { get; set; }
        public int ContentID { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<int> WatchedSeconds { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual User User { get; set; }
    }
}
